apiVersion: v1
kind: Service
metadata:
  name: coderco-task-manager-service
spec:
  selector:
    app: coderco-task-manager
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 3000  
  type: ClusterIP
